"""Add MoodLog table

Revision ID: 31b69e56b776
Revises: 807dc6f77f37
Create Date: 2025-10-08 16:50:29.197681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31b69e56b776'
down_revision = '807dc6f77f37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mood_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mood_score', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mood_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mood_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_mood_logs_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mood_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mood_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_mood_logs_created_at'))

    op.drop_table('mood_logs')
    # ### end Alembic commands ###
