"""Add notes column to breathing_exercise_logs table

Revision ID: 4eaba787b265
Revises: 720b79c9f112
Create Date: 2025-09-19 21:59:01.028031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4eaba787b265'
down_revision = '720b79c9f112'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('breathing_exercise_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('breathing_exercise_logs', schema=None) as batch_op:
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
