"""Initial migration.

Revision ID: 604ad16668c5
Revises: 
Create Date: 2025-09-26 10:29:37.851234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '604ad16668c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
