"""Add rejection_reason and updated_at to appointments

Revision ID: 807dc6f77f37
Revises: c62c062b2628
Create Date: 2025-10-05 23:46:27.302335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '807dc6f77f37'
down_revision = 'c62c062b2628'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('music_therapy_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mood', sa.String(length=50), nullable=False),
    sa.Column('brainwave', sa.String(length=20), nullable=True),
    sa.Column('frequency', sa.Float(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('music_therapy_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_music_therapy_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_music_therapy_logs_user_id'), ['user_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_recipient_id'), ['recipient_id'], unique=False)

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rejection_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('rejection_reason')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_recipient_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('music_therapy_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_music_therapy_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_music_therapy_logs_created_at'))

    op.drop_table('music_therapy_logs')
    # ### end Alembic commands ###
