"""Add ai_insights column to assessments

Revision ID: 826de8504753
Revises: 
Create Date: 2025-08-24 16:26:22.597226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '826de8504753'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_insights', sa.Text(), nullable=True))
        batch_op.drop_column('ai_analysis')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_analysis', sa.TEXT(), nullable=True))
        batch_op.drop_column('ai_insights')

    # ### end Alembic commands ###
