"""add binaural_tracks

Revision ID: c62c062b2628
Revises: 27e5a14fe003
Create Date: 2025-10-05 21:13:09.444428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c62c062b2628'
down_revision = '27e5a14fe003'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('binaural_tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('artist', sa.String(length=200), nullable=True),
    sa.Column('emotion', sa.String(length=100), nullable=True),
    sa.Column('youtube_id', sa.String(length=100), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('source_file', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('binaural_tracks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_binaural_tracks_emotion'), ['emotion'], unique=False)
        batch_op.create_index(batch_op.f('ix_binaural_tracks_youtube_id'), ['youtube_id'], unique=False)

    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.create_index('idx_assessment_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index('idx_assessment_user_type', ['user_id', 'assessment_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessments_assessment_type'), ['assessment_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessments_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('digital_detox_logs', schema=None) as batch_op:
        batch_op.create_index('idx_detox_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index('idx_detox_user_date', ['user_id', 'date'], unique=False)
        batch_op.create_index(batch_op.f('ix_digital_detox_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_digital_detox_logs_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_digital_detox_logs_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_user_email_role', ['email', 'role'], unique=False)
        batch_op.create_index('idx_user_role_institution', ['role', 'institution'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_google_id'), ['google_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_institution'), ['institution'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_last_assessment_at'), ['last_assessment_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_last_assessment_at'))
        batch_op.drop_index(batch_op.f('ix_users_institution'))
        batch_op.drop_index(batch_op.f('ix_users_google_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_created_at'))
        batch_op.drop_index('idx_user_role_institution')
        batch_op.drop_index('idx_user_email_role')

    with op.batch_alter_table('digital_detox_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_digital_detox_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_digital_detox_logs_date'))
        batch_op.drop_index(batch_op.f('ix_digital_detox_logs_created_at'))
        batch_op.drop_index('idx_detox_user_date')
        batch_op.drop_index('idx_detox_user_created')

    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessments_user_id'))
        batch_op.drop_index(batch_op.f('ix_assessments_created_at'))
        batch_op.drop_index(batch_op.f('ix_assessments_assessment_type'))
        batch_op.drop_index('idx_assessment_user_type')
        batch_op.drop_index('idx_assessment_user_created')

    with op.batch_alter_table('binaural_tracks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_binaural_tracks_youtube_id'))
        batch_op.drop_index(batch_op.f('ix_binaural_tracks_emotion'))

    op.drop_table('binaural_tracks')
    # ### end Alembic commands ###
